---
server :
  port : 8888

spring :
    cloud :
       config :
          server :
            git :
              uri : https://github.com/PHarlapur/pringboot-cloud-config
              username : PHarlapur
              password : digvijayg1